[build-system]
requires = ["setuptools>=75"]
build-backend = "setuptools.build_meta"

[project]
name = "openstreetmap-full-history"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = ["pyarrow>=18", "osmium>=4.3"]

[project.optional-dependencies]
dev = ["pytest>=8"]

[tool.setuptools]
py-modules = []
